// Centralized category definitions to ensure consistency across the application

export const JOB_CATEGORIES = [
  { id: 'development', name: 'Development' },
  { id: 'design', name: 'Design & Creative' },
  { id: 'marketing', name: 'Marketing' },
  { id: 'community', name: 'Community & Social' },
  { id: 'business', name: 'Business Development' },
  { id: 'content', name: 'Content Creation' },
  { id: 'defi', name: 'DeFi & Finance' },
  { id: 'nft', name: 'NFT & Digital Assets' },
  { id: 'security', name: 'Security & Auditing' },
  { id: 'research', name: 'Research & Analysis' },
];

export const JOB_CATEGORIES_WITH_ALL = [
  { id: 'all', name: 'All Categories' },
  ...JOB_CATEGORIES,
];

export const PROJECT_CATEGORIES = [
  'AI',
  'Alpha Group',
  'Book Publishing',
  'Bridge',
  'CEX',
  'Cloud Services',
  'Compute',
  'Currency',
  'DAO',
  'DeFi',
  'DePIN',
  'Derivatives',
  'DEX',
  'DEX Aggregator',
  'Education',
  'Gaming',
  'Index Funds',
  'Infrastructure',
  'Launchpad',
  'Layer 2',
  'Lend/Borrow',
  'Liquid Staking',
  'Memecoin',
  'Metaverse',
  'Music',
  'NFT',
  'NFT Infrastructure',
  'NFT Marketplace',
  'Oracle',
  'PoW Mining',
  'Prediction Market',
  'Privacy',
  'Reserve Coin',
  'RWA',
  'SocialFi',
  'Stablecoin',
  'Storage',
  'Synthetics',
  'Telecoms',
  'Token Distribution',
  'Tools',
  'Utility',
  'Wallet',
  'Wrapped Token',
  'Yield',
  'Yield Products',
  'Other'
];
