// Centralized category definitions to ensure consistency across the application

export const JOB_CATEGORIES = [
  { id: 'development', name: 'Development' },
  { id: 'design', name: 'Design' },
  { id: 'marketing', name: 'Marketing' },
  { id: 'community', name: 'Community' },
  { id: 'business', name: 'Business' },
  { id: 'content', name: 'Content' },
  { id: 'defi', name: 'DeFi' },
  { id: 'nft', name: 'NFT' },
  { id: 'security', name: 'Security' },
  { id: 'research', name: 'Research' },
  { id: 'blockchain', name: 'Blockchain' },
  { id: 'smart-contracts', name: 'Smart Contracts' },
  { id: 'devops', name: 'DevOps' },
  { id: 'qa', name: 'QA Testing' },
  { id: 'product', name: 'Product' },
  { id: 'data', name: 'Data Science' },
  { id: 'tokenomics', name: 'Tokenomics' },
  { id: 'governance', name: 'Governance' },
  { id: 'legal', name: 'Legal' },
  { id: 'finance', name: 'Finance' },
  { id: 'operations', name: 'Operations' },
  { id: 'education', name: 'Education' },
  { id: 'translation', name: 'Translation' },
  { id: 'partnerships', name: 'Partnerships' },
  { id: 'sales', name: 'Sales' },
  { id: 'support', name: 'Support' },
  { id: 'catalyst', name: 'Catalyst' },
];

export const JOB_CATEGORIES_WITH_ALL = [
  { id: 'all', name: 'All Categories' },
  ...JOB_CATEGORIES,
];

export const PROJECT_CATEGORIES = [
  'AI',
  'Analytics',
  'API Services',
  'Bridge',
  'CEX',
  'Compute',
  'Cross-chain',
  'Currency',
  'DAO',
  'DeFi',
  'DePIN',
  'Derivatives',
  'DEX',
  'Documentation',
  'Education',
  'Enterprise',
  'Explorer',
  'Gaming',
  'Governance',
  'Identity',
  'Infrastructure',
  'Insurance',
  'IoT',
  'Launchpad',
  'Layer 2',
  'Lending',
  'Liquid Staking',
  'Marketplace',
  'Memecoin',
  'Metaverse',
  'Mobile',
  'Music',
  'NFT',
  'Oracle',
  'Payment',
  'Prediction Market',
  'Privacy',
  'RWA',
  'SDK/Library',
  'Security',
  'SocialFi',
  'Stablecoin',
  'Staking Pool',
  'Storage',
  'Supply Chain',
  'Synthetics',
  'Tools',
  'Trading Bot',
  'Utility',
  'Validator',
  'Wallet',
  'Web3',
  'Yield',
  'Other'
];
